/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    Banner: typeof import('./components/home/Banner.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    Byncsa: typeof import('./components/layouts/Byncsa.vue')['default']
    Cn: typeof import('./components/organization/cn.vue')['default']
    Comment01: typeof import('./components/comment/comment01.vue')['default']
    Comment02: typeof import('./components/comment/comment02.vue')['default']
    Comment03: typeof import('./components/comment/comment03.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Eu: typeof import('./components/organization/eu.vue')['default']
    Home: typeof import('./components/home/Home.vue')['default']
    Introduction: typeof import('./components/home/Introduction.vue')['default']
    Logos: typeof import('./components/home/Logos.vue')['default']
    MainPage: typeof import('./components/MainPage.vue')['default']
    Map: typeof import('./components/basic/map.vue')['default']
    MarkdownViewer: typeof import('./components/MarkdownViewer.vue')['default']
    Nasa: typeof import('./components/organization/nasa.vue')['default']
    Post01: typeof import('./components/post/post01.vue')['default']
    Post02: typeof import('./components/post/post02.vue')['default']
    Post03: typeof import('./components/post/post03.vue')['default']
    Post04: typeof import('./components/post/post04.vue')['default']
    QA: typeof import('./components/QA.vue')['default']
    Resources: typeof import('./components/Resources.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spacex: typeof import('./components/organization/spacex.vue')['default']
    Summary: typeof import('./components/basic/summary.vue')['default']
  }
}
